version: '3.7'

services:
  web:
    build: .
    command: ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0", "-bmanagement", "0.0.0.0"]
    volumes:
      - ./deployments:/opt/jboss/wildfly/standalone/deployments
    ports:
      - "8080:8080"
      - "9990:9990"
      - "8787:8787"